config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/', to: 'welcome#index'

  resources :coins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  layout "adm"

  before_action :set_coin, only: %i[ show edit update destroy ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @meu_nome = params[:nome]
    @curso = params[:curso]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def data_br(data_us)
        data_us.strftime("%d/%m/%Y")
    end

    def nome_aplicacao
        "Crypto Wallet App"
    end

    def ambiente_rails
        if Rails.env.development?
            "Desenvolvimento"
        elsif Rails.env.production?
            "Produção"
        else
            "Teste"
        end
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <p>
    <strong>Description:</strong>
    <%= coin.description %>
  </p>

  <p>
    <strong>Acronym:</strong>
    <%= coin.acronym %>
  </p>

  <p>
    <strong>Url image:</strong>
    <%= coin.url_image %>
  </p>

</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.label :url_image, style: "display: block" %>
    <%= form.text_field :url_image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Show this coin", @coin %> |
  <%= link_to "Back to coins", coins_path %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Moedas</h1>

<%# <h1><%= Coin.model_name.human(count: @coins.count) %>
<table class="table table-hover, container">
  <thead>
    <tr>
      <th><%= @coins.human_attribute_name(:descrição) %></th>
      <th><%= @coins.human_attribute_name(:sigla) %></th>
      <th><%= @coins.human_attribute_name(:imagem) %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, size: "25x25" %> </td>
        <td><%= link_to t('links.Mostrar'), coin %></td>
        <td><%= link_to t('links.editar'), edit_coin_path(coin) %></td>
        <td><%= link_to t('links.deletar'), coin, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new.Add Moeda'), new_coin_path, class:"btn btn-primary" %>

app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Back to coins", coins_path %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
  <%= link_to "Editar essa moeda", edit_coin_path(@coin) %> |
  <%= link_to "voltar para moedas", coins_path %>

  <%= button_to "Deletar essa moeda", @coin, method: :delete %>
</div>

app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# <h1>Cabeçalho Administrativo</h1> %>
    <%= yield %>
  </body>
  <%# <h1>Rodapé Administrativo</h1> %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/_menu.html.erb
<ul>
    <li>
        <a href="/coins/new"> Add Moedas</a>
    </li>
    <li>
        <%= link_to "Mostrar Moedas", "/coins" %>
    </li>
    <li>
        <%= link_to "Moedas", coins_path %>
    </li>
</ul>

app/views/welcome/index.html.erb
<h1>Seja Bem-Vindo(a)!</h1>
<p><strong>Data:</strong> <%= data_br(Date.today) %></p>

<%# <%nome = "Thainara"%>
<%# <p>Meu nome de trás para frente é: <%= nome.reverse.upcase %>
<%# <>a data de hoje é: <%= Date.today %>

<%= render "menu" %> <!--Partials, buscando menu no arquivo _menu.html.erb-->

<p> Você está em ambiente de <strong> <%= ambiente_rails %> </strong> </p> <!--Ambiente rails é um helper -->
<p>Meu nome é: <strong><%= @meu_nome %></strong></p> <!--variável de instância/sessão-->
<p>Meu curso é: <strong><%= @curso %></strong>